let start = document.getElementById("start"),
    budgetValue = document.getElementsByClassName("budget-value"),
    daybudgetValue = document.getElementsByClassName("daybudget-value"),
    levelValue = document.getElementsByClassName("level-value"),
    expensesValue = document.getElementsByClassName("expenses-value"),
    optionalexpensesValue = document.getElementsByClassName("optionalexpenses-value"),
    incomeValue = document.getElementsByClassName("income-value"),
    monthsavingsValue = document.getElementsByClassName("monthsavings-value"),
    yearsavingsValue = document.getElementsByClassName("yearsavings-value"),
    yearValue = document.getElementsByClassName("year-value"),
    monthValue = document.getElementsByClassName("month-value"),
    dayValue = document.getElementsByClassName("day-value"),
    expensesItem1 = document.getElementsByClassName("expenses-item")[0],
    expensesItem2 = document.getElementsByClassName("expenses-item")[1],
    expensesItem3 = document.getElementsByClassName("expenses-item")[2],
    expensesItem4 = document.getElementsByClassName("expenses-item")[3],
    button1 = document.getElementsByTagName("button")[0],
    button2 = document.getElementsByTagName("button")[1],
    button3 = document.getElementsByTagName("button")[2],
    optionalexpensesItem1 = document.querySelectorAll(".optionalexpenses-item")[0],
    optionalexpensesItem2 = document.querySelectorAll(".optionalexpenses-item")[1],
    optionalexpensesItem3 = document.querySelectorAll(".optionalexpenses-item")[2],
    chooseIncomeLabel = document.querySelector(".choose-income-label"),
    checksavings = document.querySelector(".checksavings"),
    chooseSum = document.querySelector(".choose-sum"),
    choosePercent = document.querySelector(".choose-percent");



